CREATE DATABASE PUBLICACIONES;
USE PUBLICACIONES;
-- CREANDO LAS TABLAS
CREATE TABLE CURSO(
COD_CURSO INT PRIMARY KEY auto_increment,
NOMBRE VARCHAR(50),
DESCRIPCION VARCHAR(50)
);
CREATE TABLE PUBLICACION(
COD_PUBLICACION INT PRIMARY KEY auto_increment,
COD_CURSO INT,
FOREIGN KEY(COD_CURSO) REFERENCES CURSO(COD_CURSO),
TITULO VARCHAR(50),
SEMANA VARCHAR(2),
FECHA DATE
);
CREATE TABLE USUARIO(
    COD_USUARIO INT PRIMARY KEY auto_increment,
    NOMBRE VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(100)
);
-- STORE PROCEDURE INSERT
DELIMITER $
CREATE PROCEDURE SP_CURSO_INSERT(
IN NOMBRE_IN VARCHAR(50),
IN DESCRIPCION_IN VARCHAR(50)
)
BEGIN
INSERT INTO CURSO(NOMBRE,DESCRIPCION)
VALUES
(NOMBRE_IN,DESCRIPCION_IN);
END
$
-- EJECUTAR SP INSERT
CALL SP_CURSO_INSERT('LARAVEL','FRAMEWORK DE PHP');

-- STORE PROCEDURE SELECT
DELIMITER $
CREATE PROCEDURE SP_CURSO_SELECT()
BEGIN
SELECT * FROM CURSO;
END
$
-- EJECUTAR SP SELECT
CALL SP_CURSO_SELECT;

-- STORE PROCEDURE UPDATE
DELIMITER $
CREATE PROCEDURE SP_CURSO_UPDATE(
IN COD_CURSO_IN INT,
IN NOMBRE_IN VARCHAR(50),
IN DESCRIPCION_IN VARCHAR(50)
)
BEGIN
UPDATE CURSO SET
NOMBRE = NOMBRE_IN,
DESCRIPCION = DESCRIPCION_IN
WHERE
COD_CURSO = COD_CURSO_IN;
END
$
-- EJECUTAR SP UPDATE
CALL SP_CURSO_UPDATE(1,'LARAVEL','FRAMEWORK FACIL DE PHP');
-- STORE PROCEDURE DELETE
DELIMITER $
CREATE PROCEDURE SP_CURSO_DELETE(
IN COD_CURSO_IN INT
)
BEGIN
DELETE FROM CURSO
WHERE
COD_CURSO = COD_CURSO_IN;
END
$
-- EJECUTAR SP DELETE
CALL SP_CURSO_DELETE(1);

-- STORE PROCEDURE LOGIN 
DELIMITER $
CREATE PROCEDURE SP_USUARIO_LOGIN(
IN NOMBRE_IN VARCHAR(50),
PASSWORD_IN VARCHAR(100)
)
BEGIN
SELECT COD_USUARIO, NOMBRE FROM USUARIO
WHERE
NOMBRE = NOMBRE_IN AND PASSWORD = PASSWORD_IN;
END $

-- INSERTANDO UN USARIO
INSERT INTO USUARIO(NOMBRE,PASSWORD)
VALUES
('ANTHONYCODE','1234');
-- LOGIN
CALL SP_USUARIO_LOGIN('ANTHONYCODE','1234');