-- CREANDO LA BASE DE DATOS
CREATE DATABASE PUBLICACIONES;
USE PUBLICACIONES;
-- CREANDO LAS TABLAS
CREATE TABLE CURSO(
COD_CURSO INT PRIMARY KEY IDENTITY,
NOMBRE VARCHAR(50),
DESCRIPCION VARCHAR(50)
);
CREATE TABLE PUBLICACION(
COD_PUBLICACION INT PRIMARY KEY IDENTITY,
COD_CURSO INT,
FOREIGN KEY(COD_CURSO) REFERENCES CURSO(COD_CURSO),
TITULO VARCHAR(50),
SEMANA VARCHAR(2),
FECHA DATE
);

CREATE TABLE USUARIO(
    COD_USUARIO INT PRIMARY KEY IDENTITY,
    NOMBRE VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(100)
);
GO
-- PROCEDIMIENTOS ALMACENADOS PARA UN CRUD
-- CRUD
-- C INSERT
-- R SELECT
-- U UPDATE
-- D DELETE

-- C INSERT
CREATE PROCEDURE SP_USUARIO_INSERT(
@NOMBRE VARCHAR(50),
@PASSWORD VARCHAR(100)
)
AS
BEGIN
	INSERT INTO USUARIO(NOMBRE,PASSWORD)
	VALUES
	(@NOMBRE,@PASSWORD);
END
GO



-- R SELECT
CREATE PROCEDURE SP_USUARIO_SELECT
AS
BEGIN
	SELECT * FROM USUARIO;
END
GO
-- U UPDATE
CREATE PROCEDURE SP_USUARIO_UPDATE(
@COD_USUARIO INT,
@NOMBRE VARCHAR(50),
@PASSWORD VARCHAR(100)
)
AS
BEGIN
	UPDATE USUARIO SET
	NOMBRE = @NOMBRE,
	PASSWORD = @PASSWORD
	WHERE COD_USUARIO = @COD_USUARIO;
END
GO

-- D DELETE
CREATE PROCEDURE SP_USUARIO_DELETE(
@COD_USUARIO INT
)
AS
BEGIN
	DELETE FROM USUARIO
	WHERE COD_USUARIO = @COD_USUARIO;
END
GO
-- SP USUARIO LOGIN
CREATE PROCEDURE SP_USUARIO_LOGIN(
@NOMBRE VARCHAR(50),
@PASSWORD VARCHAR(100)
)
AS
BEGIN
	SELECT * FROM USUARIO 
	WHERE NOMBRE =@NOMBRE AND PASSWORD =@PASSWORD;
END


-- EJECUTAR SP
EXECUTE SP_USUARIO_SELECT;
-- EJECUTAR SP
EXECUTE SP_USUARIO_LOGIN 'PEDRO','1234';

-- EJECUTAR SP
EXECUTE SP_USUARIO_INSERT 'ANTHONY','1234';
-- EJECUTAR SP
EXECUTE SP_USUARIO_DELETE 1;
-- EJECUTAR SP
EXECUTE SP_USUARIO_UPDATE 1,'PEDRO','1234';